[phases.setup]
nixPkgs = ["python311", "python311Packages.pip"]

[phases.build]
pythonRequirements = "src/main/resources/python/requirements.txt"

[start]
cmd = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
