[phases.setup]
nixPkgs = ["openjdk17", "python311", "python311Packages.pip"]

[phases.build]
cmds = [
  "chmod +x ./mvnw",
  "./mvnw -B -DskipTests clean install"
]
pythonRequirements = "src/main/resources/python/requirements.txt"

[start]
cmd = "java -jar target/backend-0.0.1-SNAPSHOT.jar"
